<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-19T16:21:40 BRT" name="Default suite" finished-at="2021-06-19T16:22:37 BRT" duration-ms="56210">
    <groups>
    </groups>
    <test started-at="2021-06-19T16:21:40 BRT" name="Default test" finished-at="2021-06-19T16:22:37 BRT" duration-ms="56210">
      <class name="executor_cucumber.Runner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:executor_cucumber.Runner@1fde5d22]" started-at="2021-06-19T16:21:40 BRT" name="setUpClass" finished-at="2021-06-19T16:21:41 BRT" duration-ms="504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runTest(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:executor_cucumber.Runner@1fde5d22]" started-at="2021-06-19T16:21:41 BRT" name="runTest" data-provider="features" finished-at="2021-06-19T16:22:35 BRT" duration-ms="54459" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Cadastrar Usuario]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[org.junit.ComparisonFailure: expected:<[Sending e-mail success!]> but was:<[« Send »]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: org.junit.ComparisonFailure: expected:<[Sending e-mail success!]> but was:<[« Send »]>
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at executor_cucumber.Runner.runTest(Runner.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.junit.ComparisonFailure: expected:<[Sending e-mail success!]> but was:<[« Send »]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at steps.AdicionarProdutoStep.valido_a_mensagem_email_enviado_com_sucesso(AdicionarProdutoStep.java:108)
at ✽.Entao valido a mensagem email enviado com sucesso(src/test/java/features/CadastrarUsuario.feature:53)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTest -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:executor_cucumber.Runner@1fde5d22]" started-at="2021-06-19T16:22:36 BRT" name="afterClass" finished-at="2021-06-19T16:22:37 BRT" duration-ms="836" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- executor_cucumber.Runner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
